### ISSUE TITLE
[BUG] - Resume button not working 

### ISSUE THREAD

**Issue by mcjill** [CommunityPro/portfolio-html#138] opened 2023-06-14 11:35 UTC
The resume button is not functioning as intended. Its purpose is to allow potential recruiters to download the your resume and take a glance at it. However, when the button is clicked, the resume file is not being downloaded.

**Comment by Evavic44** [comment] 2023-06-15 15:44
Hey Elliot. This portfolio is acting as a template for anyone that wants to use it and as such, we leave the functionality of certain elements like the resume to the user's discretion. 

So it is not a bug but an intended feature. So I'll be closing this issue. 
Thanks for your contribution. Feel free to look at other potential issues. 👍

**Closed by Evavic44** 2023-06-15 15:44 UTC
Labels: bug
