### ISSUE TITLE
[BUG] - 

### ISSUE THREAD

**Issue by manishbajagai2** [CommunityPro/portfolio-html#78] opened 2022-01-22 20:19 UTC
## Github page is not working
The deployed website on Github Pages in not working

## To Reproduce
1. Go to Environments
2. Click on github-pages
3. Click on View Deployment

## Expected behavior
The website should be displayed on the web

## Screenshots
![image](https://user-images.githubusercontent.com/62448303/150654170-1bc85ca6-2c63-4ef0-a8e6-7a1139e080c9.png)

## Laptop:
 - OS: [macOS]
 - Browser [chrome]
 - Version [ 97.0.4692.99]

**Comment by Evavic44** [comment] 2022-01-22 20:23
Thanks for raising this issue @manishbajagai2 do you have a fix for this?

**Comment by vermilion4** [comment] 2022-01-22 20:26
The problem is index.html is not at the root of the repo

**Comment by vermilion4** [comment] 2022-01-22 20:26
Github pages won't work unless the folder is restructured that way

**Comment by Evavic44** [comment] 2022-01-22 20:29
> Github pages won't work unless the folder is restructured that way

Surely that can't be right. 🤔 Isn't there a way to configure it?

**Comment by vermilion4** [comment] 2022-01-22 20:37
There's another method I can try...assign it to me

**Comment by vermilion4** [comment] 2022-01-22 20:39
Also I need access to the repo

**Comment by manishbajagai2** [comment] 2022-01-22 20:41
if possible i too would like to have it a go

**Comment by manishbajagai2** [comment] 2022-01-22 20:42
Let @vermilion4 try. If she does then fine otherwise @Evavic44 can assign to me again

**Comment by Evavic44** [comment] 2022-01-22 20:48
Thank you. @manishbajagai2 🙌🏾💯

**Comment by Evavic44** [comment] 2022-01-22 20:49
@vermilion4 i've assigned you. Give me a few minutes to configure the access. 💯

**Comment by vermilion4** [comment] 2022-01-22 21:33
thanks @Evavic44 .done now

**Comment by vermilion4** [comment] 2022-01-22 21:33
@manishbajagai2 check again if it works now

**Comment by Evavic44** [comment] 2022-01-22 21:36
What link are you using, I still see the error. @vermilion4

**Comment by Evavic44** [comment] 2022-01-22 21:41
Okay fixed. I've seen it now. Thanks, @vermilion4 👍🏾 Must the folder be named docs? Would have preferred the `template` we had. What do you think?

**Closed by Evavic44** 2022-01-22 21:41 UTC
Labels: bug, help wanted

**Comment by vermilion4** [comment] 2022-01-22 21:52
@Evavic44 ok I can work it with templates, the problem is what the url will look like. It would be communitypro.github.io/portfolio-html/template/index.html which isn't very user friendly compared to communitypro.github.io/portfolio-html. But if you're fine with that all the same,  I can try that. Also I'll have to create an index.html in the root which would now redirect to the template folder since github pages supports only root/docs folder. So should I still switch it to template?

**Comment by Evavic44** [comment] 2022-01-22 22:00
> @Evavic44 ok I can work it with templates, the problem is what the url will look like. It would be communitypro.github.io/portfolio-html/template/index.html which isn't very user friendly compared to communitypro.github.io/portfolio-html. But if you're fine with that all the same, I can try that. Also I'll have to create an index.html in the root which would now redirect to the template folder since github pages supports only root/docs folder. So should I still switch it to template?

Nah. That would be too confusing, let's work with this.
